#!/bin/bash

# === Functions ===
function cd {
    builtin cd "$1"
    ls
}

function mkcd {
    mkdir -p $1
    cd $1
}

function ebrc {
    lvim ~/bashrc_ext
    source ~/.bashrc
}

function evim {
    lvim ~/.config/lvim/config.lua
}

# === Aliases ===
alias bat=batcat
alias e=lvim
alias g=gitui
alias m=make
alias Nala="sudo nala"
alias o=xdg-open
alias plz='sudo $(history -p !!)'
alias r=trash
alias rm=trash
alias sc=sc-im
alias vi='lvim'
alias vim='lvim'

# === Exports ===
export EDITOR=lvim
export PATH="$PATH:$(go env GOPATH)/bin:/usr/local/texlive/2022/bin/x86_64-linux"
export VISUAL=lvim

# === Variables ===
LS_COLORS+=':ow=01;33'

# === Keybindngs ===
set -o vi
bind '"ht":vi-movement-mode'

# === Environment === 
. "$HOME/.cargo/env"
source /usr/share/doc/fzf/examples/key-bindings.bash

[[ ! -z $SSH_TTY ]] && neofetch
[[ -f $HOME/bashrc_ext_local ]] && source $HOME/bashrc_ext_local
