#!/bin/bash

function cd {
    builtin cd $1
    ls
}

function mkcd {
    mkdir $1
    cd $1
}

function ebrc {
    lvim ~/bashrc_ext
    source ~/.bashrc
}

function evim {
    lvim ~/.config/lvim/config.lua
}

alias e=lvim

export VISUAL=lvim
export EDITOR=lvim

export PATH="$PATH:$(go env GOPATH)/bin"

set -o vi
bind '"ht":vi-movement-mode'

[[ ! -z $SSH_TTY ]] && neofetch
