#!/bin/bash

function cd {
    builtin cd $1
    ls
}

function mkcd {
    mkdir $1
    cd $1
}

function ebash {
    nvim ~/bash_ext
    source ~/.bashrc
}

function evim {
    nvim ~/.config/nvim/init.vim
}

alias e=nvim

export VISUAL=nvim
export EDITOR=nvim

export PATH="$PATH:$(go env GOPATH)/bin"

[[ ! -z $SSH_TTY ]] && neofetch
